services:
  api:
    build: ./api
    container_name: helpdesk-api

    environment:
      DATABASE_HOST: postgres
      DATABASE_NAME: helpdesk
      DATABASE_USER: helpdesk
      DATABASE_PASSWORD: password
      REDIS_HOST: redis

    depends_on:
      - postgres
      - redis

    ports:
      - "8000:8000"

    networks:
      - frontend_network
      - backend_network

  frontend:
    build: ./frontend
    container_name: helpdesk-frontend

    ports:
      - "8081:80"

    networks:
      - frontend_network

  postgres:
    image: postgres:17
    container_name: helpdesk-postgres

    environment:
      POSTGRES_DB: helpdesk
      POSTGRES_USER: helpdesk
      POSTGRES_PASSWORD: password

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - backend_network

  redis:
    image: redis:8-alpine
    container_name: helpdesk-redis

    networks:
      - backend_network

volumes:
  postgres_data:

networks:
  frontend_network:
  backend_network: