services:
  api:
    build: ./api
    container_name: helpdesk-api

    environment:
      DATABASE_HOST: postgres
      DATABASE_NAME: helpdesk
      DATABASE_USER: helpdesk
      DATABASE_PASSWORD: password
      REDIS_HOST: redis

    depends_on:
      - postgres
      - redis

    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: helpdesk-frontend

    ports:
      - "8081:80"

  postgres:
    image: postgres:17
    container_name: helpdesk-postgres

    environment:
      POSTGRES_DB: helpdesk
      POSTGRES_USER: helpdesk
      POSTGRES_PASSWORD: password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:8-alpine
    container_name: helpdesk-redis

    ports:
      - "6379:6379"

volumes:
  postgres_data: